blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/williambdean/latent-calendar/discussions/new
    about: Ask questions and discuss implementation and use cases
